spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/users/**
        - id: doc-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/docs/**
        - id: version-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/versions/**
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST

server:
  port: 8080
