spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/users/**
        - id: doc-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/docs/**
        - id: version-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/versions/**

        # NEW: Route raw /docs/** (for refresh calls without /api)
        - id: doc-service-direct
          uri: http://localhost:8082
          predicates:
            - Path=/docs/**

        # NEW: Route websocket
        - id: doc-service-ws
          uri: http://localhost:8082
          predicates:
            - Path=/ws/**
      
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST

server:
  port: 8080
