server:
  port: 8081

spring:
  datasource:
    # Use file-based H2 so registered users persist across backend restarts
    url: jdbc:h2:file:./data/userdb;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
